services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./MoTR/run_motr_in_magpie/attachment:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    tty: true